# 此配置仅适用于Clash Verge/ClashMetaForAndroid,其他ClashMeta客户端未经测试
# 更新时间: 2024-2-13 12:45
# 来源：https://github.com/Repcz/Tool/blob/X/Clash/Meta/ClashVerge.yaml


mixed-port: 7893      # 混合端口 HTTP和SOCKS5用一个端口
geodata-mode: true    #【Meta专属】使用geoip.dat数据库(默认：false使用mmdb数据库)
tcp-concurrent: false #【Meta专属】TCP 并发连接所有 IP, 将使用最快握手的 TCP
allow-lan: true       # 允许局域网的连接（可用来共享代理）
bind-address: "*"     # 仅在将allow-lan设置为true时适用
                      # #"*": 绑定所有IP地址
find-process-mode: strict           #匹配所有进程（always/strict/off）
ipv6: false           # 开启 IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录
mode: rule            # 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）/ script (脚本)
log-level: info       # 设置日志输出级别 (5 个级别：silent / error / warning / info / debug）
external-controller: 0.0.0.0:9093   #外部控制器,可以使用 RESTful API 来控制你的 clash 内核
global-client-fingerprint: chrome   #全局 TLS 指纹，优先低于 proxy 内的 client-fingerprint
                                    #可选： "chrome","firefox","safari","ios","random","none" options.


profile:
  store-selected: true # 存储 select 选择记录
  store-fake-ip: true  # 持久化 fake-ip
  
sniffer:               # 嗅探域名 可选配置
  enable: true
  parse-pure-ip: true  # 是否使用嗅探结果作为实际访问，默认 true
  sniff:
    TLS:               # TLS 默认嗅探 443
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    QUIC:
      ports: [443, 8443]
      
tun:                   # Tun 配置
  enable: true
  stack: system        # 可选： system/gvisor/mixed；tun 模式堆栈,如无使用问题,建议使用 system 栈;MacOS 用户推荐 gvisor栈
                       # system 使用系统协议栈,可以提供更稳定/全面的 tun 体验,且占用相对其他堆栈更低。 
                       # gvisor 通过在用户空间中实现网络协议栈,可以提供更高的安全性和隔离性,同时可以避免操作系统内核和用户空间之间的切换,从而在特定情况下具有更好的网络处理性能
                       # mixed 混合堆栈,tcp使用 system栈,udp使用 gvisor栈,使用体验可能相对更好
  dns-hijack: [any:53]            # dns劫持,一般设置为 any:53 即可, 即劫持所有53端口的udp流量
# strict_route: true   # 将所有连接路由到tun来防止泄漏，但你的设备将无法其他设备被访问
  auto-route: true     # 自动设置全局路由，可以自动将全局流量路由进入tun网卡。
  auto-detect-interface: true     # 自动识别出口网卡
        
dns:
  enable: true             # 关闭将使用系统 DNS
  ipv6: false              # IPV6解析开关；如果为false，将返回ipv6结果为空
  enhanced-mode: fake-ip   # 模式：redir-host或fake-ip
  listen: 0.0.0.0:53       # DNS监听地址
  fake-ip-range: 198.18.0.1/16    # Fake-IP解析地址池
  fake-ip-filter: ['*.lan', 'cable.auth.com', '*.msftconnecttest.com', '*.msftncsi.com', 'network-test.debian.org', 'detectportal.firefox.com', 'resolver1.opendns.com', '*.srv.nintendo.net', '*.stun.playstation.net', 'xbox.*.microsoft.com', '*.xboxlive.com', 'stun.*', 'global.turn.twilio.com', 'global.stun.twilio.com', 'localhost.*.qq.com', 'localhost.*.weixin.qq.com', '*.logon.battlenet.com.cn', '*.logon.battle.net', '*.blzstatic.cn', 'music.163.com', '*.music.163.com', '*.126.net', 'musicapi.taihe.com', 'music.taihe.com', 'songsearch.kugou.com', 'trackercdn.kugou.com', '*.kuwo.cn', 'api-jooxtt.sanook.com', 'api.joox.com', 'joox.com', 'y.qq.com', '*.y.qq.com', 'streamoc.music.tc.qq.com', 'mobileoc.music.tc.qq.com', 'isure.stream.qqmusic.qq.com', 'dl.stream.qqmusic.qq.com', 'aqqmusic.tc.qq.com', 'amobile.music.tc.qq.com', '*.xiami.com', '*.music.migu.cn', 'music.migu.cn', 'proxy.golang.org', '*.mcdn.bilivideo.cn', '*.cmpassport.com', 'id6.me', 'open.e.189.cn', 'mdn.open.wo.cn', 'opencloud.wostore.cn', 'auth.wosms.cn', '*.jegotrip.com.cn', '*.icitymobile.mobi', '*.pingan.com.cn', '*.cmbchina.com', 'pool.ntp.org', '*.pool.ntp.org', 'ntp.*.com', 'time.*.com', 'ntp?.*.com', 'time?.*.com', 'time.*.gov', 'time.*.edu.cn', '*.ntp.org.cn', 'PDC._msDCS.*.*', 'DC._msDCS.*.*', 'GC._msDCS.*.*']
                          # fake ip 白名单列表'以下地址不会下发fakeip映射用于连接
  nameserver: [https://doh.pub/dns-query, https://dns.alidns.com/dns-query]


########## 建立锚点 ##########

# 策略组引用相关参数
pg: &pg {type: select, proxies: [DIRECT, 香港节点, 台湾节点, 美国节点, 狮城节点, 日本节点, 韩国节点]}

# 订阅更新和延迟测试相关参数
p: &p {type: http, interval: 86400, health-check: {enable: true, url: http://www.gstatic.com/generate_204, interval: 1800}}

# 自动选择策略组：选取延迟最低节点
auto: &auto {type: url-test, lazy: true, url: http://www.gstatic.com/generate_204, interval: 900, use: [Subscribe]}

# 手动选择策略组：手动选择想要的节点/策略组
select: &select {type: select, use: [Subscribe]}

# 故障回退策略组：策略组将按顺序选择你列表中第一个可用的节点
fallback: &fallback {type: fallback, lazy: true, url: http://www.gstatic.com/generate_204, interval: 900, use: [Subscribe]}

# 负载均衡策略组：不同的请求将使用不同的代理节点
load-balance: &load-balance {type: load-balance, lazy: true, url: http://www.gstatic.com/generate_204, interval: 900, use: [Subscribe]}

# classical规则相关
c: &c {type: http, behavior: classical, interval: 86400}

# domain规则相关
d: &d {type: http, behavior: domain, interval: 86400}

# ipcidr规则相关
i: &i {type: http, behavior: ipcidr, interval: 86400}

########## 锚点结束 ##########


# 机场订阅链接
proxy-providers:
  Subscribe: {<<: *p, path: ./proxy-providers/Sub.yaml, url: http://your-service-provider}
    # 在此将"http://your-service-provider"替换为你的机场订阅，推荐使用base64或者node list
    # Sub-Store生成的链接,可以直接替换上述url引号中的部分,具体见Sub-Store教程   


proxies: null

proxy-groups:

  # 分流分组
  # 手动选择示例
  #- {name: 手动切换, type: select, use: [Subscribe], proxies: [DIRECT, 香港节点, 日本节点, 美国节点, 台湾节点, 狮城节点, 韩国节点]}

  - {name: 海外网站, <<: *pg}

  - {name: 海外媒体, <<: *pg}

  - {name: 谷歌代理, <<: *pg}

  - {name: 微软代理, <<: *pg}

  - {name: 电报代理, <<: *pg}

  - {name: 推特代理, <<: *pg}

  - {name: 游戏代理, <<: *pg}

  - {name: 苹果服务, <<: *pg}

  - {name: 哔哩哔哩, type: select, proxies: [DIRECT, 香港节点, 台湾节点]}


  # 节点地区分组
  ## auto更改为select，即为手动选择

  - {name:  香港节点, <<: *auto, filter: "(?=.*(港|HK|(?i)Hong))^((?!(台|日|韩|新|深|美)).)*$"            }

  - {name:  台湾节点, <<: *auto, filter: "(?=.*(台|TW|(?i)Taiwan))^((?!(港|日|韩|新|美)).)*$"             }

  - {name:  美国节点, <<: *auto, filter: "(?=.*(美|US|(?i)States|America))^((?!(港|台|日|韩|新)).)*$"     }

  - {name:  狮城节点, <<: *auto, filter: "(?=.*(新|狮|獅|SG|(?i)Singapore))^((?!(港|台|日|韩|美|西)).)*$" }

  - {name:  日本节点, <<: *auto, filter: "(?=.*(日|JP|(?i)Japan))^((?!(港|台|韩|新|美)).)*$"              }

  - {name:  韩国节点, <<: *auto, filter: "(?=.*(韩|KR|(?i)Korea))^((?!(台|日|港|新|美)).)*$"              }


# 分流规则
rule-providers:

 # 局域网 
 Lan:             {<<: *i, format: text, path: ./rule-providers/Lan.list,             url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Lan.list}

 # 拦截广告
 BanAD:           {<<: *c, format: text, path: ./rule-providers/BanAD.list,           url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Block/BanAD.list}
 BanEasyList:     {<<: *c, format: text, path: ./rule-providers/BanEasyList.list,     url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Block/BanEasyList.list}
 BanEasyPrivacy:  {<<: *c, format: text, path: ./rule-providers/BanEasyPrivacy.list,  url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Block/BanEasyPrivacy.list}
 BlockAds:        {<<: *c, format: text, path: ./rule-providers/BlockAds.list,        url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/BlockAds.list}
 BlockAdg:        {<<: *c, format: text, path: ./rule-providers/BlockAdg.list,        url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/BlockAdg.list}
 Adrules:         {<<: *c, format: text, path: ./rule-providers/adrules.list,         url: https://adrules.top/adrules.list}

 # 谷歌服务
 YouTube:        {<<: *c, format: text, path: ./rule-providers/YouTube.list,      url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Media/YouTube.list}
 Google:         {<<: *c, format: text, path: ./rule-providers/Google.list,       url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Other/Google.list}

 # 微软服务
 GitHub:         {<<: *c, format: text, path: ./rule-providers/GitHub.list,       url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Other/GitHub.list}
 OneDrive:       {<<: *c, format: text, path: ./rule-providers/OneDrive.list,     url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Other/OneDrive.list}
 Microsoft:      {<<: *c, format: text, path: ./rule-providers/Microsoft.list,    url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Other/Microsoft.list}

 # 奈飞影视
 Netflix:        {<<: *c, format: text, path: ./rule-providers/Netflix.list,      url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Media/Netflix.list}

 # 国际抖音 
 TikTok:         {<<: *c, format: text, path: ./rule-providers/TikTok.list,       url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Media/TikTok.list}

 # ChatGPT
 OpenAI:         {<<: *c, format: text, path: ./rule-providers/OpenAI.list,       url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Other/OpenAI.list}

 # 电报信息
 Telegram:       {<<: *c, format: text, path: ./rule-providers/Telegram.list,     url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Other/Telegram.list}

 # 贝宝支付
 PayPal:        {<<: *c, format: text, path: ./rule-providers/PayPal.list,       url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Other/PayPal.list}

 # 推特加速
 Twitter:       {<<: *c, format: text, path: ./rule-providers/Twitter.list,      url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Other/Twitter.list}

 # 脸书加速
 Facebook:      {<<: *c, format: text, path: ./rule-providers/Facebook.list,     url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Other/Facebook.list}

 # 游戏加速
 Game:          {<<: *c, format: text, path: ./rule-providers/Game.list,         url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Other/Game.list}

 # 海外媒体
 GlobalMedia:   {<<: *c, format: text, path: ./rule-providers/GlobalMedia.list,  url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Media/GlobalMedia.list}

 # 国际代理
 GlobalGFW:     {<<: *c, format: text, path: ./rule-providers/GlobalGFW.list,    url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/GlobalGFW.list}

 # 苹果服务
 Apple:         {<<: *c, format: text, path: ./rule-providers/Apple.list,        url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Other/Apple.list}

 # 哔哩哔哩
 Bilibili:      {<<: *c, format: text, path: ./rule-providers/Bilibili.list,     url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Media/Bilibili.list}

 # 国内直连
 WeChat:        {<<: *c, format: text, path: ./rule-providers/WeChat.list,       url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Other/WeChat.list}
 ChinaMedia:    {<<: *c, format: text, path: ./rule-providers/ChinaMedia.list,   url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Media/ChinaMedia.list}
 China:         {<<: *c, format: text, path: ./rule-providers/Direct.list,       url: https://cdn.jsdelivr.net/gh/axcsz/Collect@master/Ruleset/Direct.list}


# 分流策略
rules:
  # RULE
  - RULE-SET,Lan,DIRECT
  - RULE-SET,BlockAds,REJECT
  - RULE-SET,BlockAdg,REJECT
  - RULE-SET,BanAD,REJECT
  - RULE-SET,BanEasyList,REJECT
  - RULE-SET,Adrules,REJECT
  - RULE-SET,BanEasyPrivacy,REJECT
  - RULE-SET,YouTube,谷歌代理
  - RULE-SET,Google,谷歌代理
  - RULE-SET,GitHub,微软代理
  - RULE-SET,OneDrive,微软代理
  - RULE-SET,Microsoft,微软代理
  - RULE-SET,Telegram,电报代理
  - RULE-SET,OpenAI,狮城节点
  - RULE-SET,Game,游戏代理
  - RULE-SET,PayPal,推特代理
  - RULE-SET,Twitter,推特代理
  - RULE-SET,Facebook,推特代理
  - RULE-SET,Netflix,海外媒体
  - RULE-SET,TikTok,海外媒体
  - RULE-SET,GlobalMedia,海外媒体
  - RULE-SET,GlobalGFW,海外网站
  - RULE-SET,Apple,苹果服务
  - RULE-SET,Bilibili,哔哩哔哩
  - RULE-SET,WeChat,DIRECT
  - RULE-SET,ChinaMedia,DIRECT
  - RULE-SET,China,DIRECT
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,海外网站


# 屏蔽443
script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
